name: Unit Tests

on: push

jobs:

  unit-tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: |
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake ..
          cmake --build .
      - name: Run google Tests
        run: ${{github.workspace}}/build/tests/unit/unit_tests